on: push
defaults:
  run:
    shell: arch -arm64 bash --noprofile --norc -eo pipefail {0}
jobs:
  testit:
    name: Test Job for M1 runner
    runs-on: [self-hosted, macOS]
    steps:
    - name: clone repo
      uses: actions/checkout@v2

    - name: do stuff
      run: |
        arch
        zsh -c 'echo hi mom from $(arch)'
        python3 -V
        pwd
        ls -la


